const actionTypes = {
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR',
  FETCH_MAN_PRODUCTS_REQUEST: 'FETCH_MAN_PRODUCTS_REQUEST',
  FETCH_MAN_PRODUCTS_SUCCESS: 'FETCH_MAN_PRODUCTS_SUCCESS',
  FETCH_MAN_PRODUCTS_ERROR: 'FETCH_MAN_PRODUCTS_ERROR',
  FETCH_WOMEN_PRODUCTS_REQUEST: 'FETCH_WOMEN_PRODUCTS_REQUEST',
  FETCH_WOMEN_PRODUCTS_SUCCESS: 'FETCH_WOMEN_PRODUCTS_SUCCESS',
  FETCH_WOMEN_PRODUCTS_ERROR: 'FETCH_WOMEN_PRODUCTS_ERROR',
};

export default actionTypes;
